# Create a nightly release at every push
name: Nightly Release
on:
  push:
    branches:
      - main
jobs:
  build:
    uses: playest/TransferStuff/.github/workflows/build.yml@main # this should be replacable by .github/workflows/build.yml soon, see here: https://github.community/t/ref-head-in-reusable-workflows/203690/34
    with:
      version: "nightly"
      leadingv: false
  update-release: # add the artifacts to the release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: echo "version=nightly" >> $GITHUB_ENV
      - name: Get module-manifest
        uses: actions/download-artifact@v2
        with:
          name: module-manifest
      - name: Get module-archive
        uses: actions/download-artifact@v2
        with:
          name: module-archive
      - run: ls -R
      - name: Update Release with Files
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          name: ${{ env.version }}
          draft: false
          prerelease: true
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: './module.json, ./transfer-stuff-${{ env.version }}.zip'
          tag: ${{ env.version }}
          omitBodyDuringUpdate: true
          omitNameDuringUpdate: true